# Generated by Django 6.0.1 on 2026-07-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0005_fund_fee_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('RSS', 'RSS'), ('HN', 'HackerNews'), ('AKSHARE', 'AkShare'), ('CUSTOM', '自定义')], default='RSS', max_length=12, verbose_name='类型')),
                ('category', models.CharField(choices=[('politics', '时政国际'), ('finance', 'A股财经'), ('tech_cn', '国内科技'), ('tech_oversea', '海外科技')], max_length=16, verbose_name='分类')),
                ('url', models.URLField(blank=True, help_text='RSS/API 地址；HN/AKSHARE 可留空', max_length=500, verbose_name='地址')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '数据源',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('content', models.TextField(blank=True, default='', verbose_name='正文')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='原文链接')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='发布时间')),
                ('category', models.CharField(choices=[('politics', '时政国际'), ('finance', 'A股财经'), ('tech_cn', '国内科技'), ('tech_oversea', '海外科技')], db_index=True, max_length=16, verbose_name='分类')),
                ('source', models.CharField(blank=True, default='', max_length=64, verbose_name='来源')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funds', models.ManyToManyField(blank=True, related_name='articles', to='funds.fund', verbose_name='关联基金')),
                ('source_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.source', verbose_name='数据源')),
            ],
            options={
                'verbose_name': '新闻',
                'ordering': ['-published_at'],
            },
        ),
    ]
