# Generated by Django 6.0.1 on 2026-07-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('politics', '时政国际'), ('finance', 'A股财经'), ('finance_oversea', '海外财经'), ('tech_cn', '国内科技'), ('tech_oversea', '海外科技')], db_index=True, max_length=16, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='source',
            name='category',
            field=models.CharField(choices=[('politics', '时政国际'), ('finance', 'A股财经'), ('finance_oversea', '海外财经'), ('tech_cn', '国内科技'), ('tech_oversea', '海外科技')], max_length=16, verbose_name='分类'),
        ),
    ]
