# Generated by Django 6.0.1 on 2026-07-30 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('morning', '午间'), ('evening', '晚间'), ('ondemand', '手动')], max_length=8)),
                ('date', models.DateField()),
                ('content_html', models.TextField(default='')),
                ('screening', models.JSONField(blank=True, default=dict)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ok', 'ok'), ('degraded', 'degraded'), ('failed', 'failed')], default='ok', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['user', '-date', 'type'], name='aiagent_ana_user_id_30872c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('type__in', ['morning', 'evening'])), fields=('user', 'type', 'date'), name='uniq_timed_report_per_day')],
            },
        ),
    ]
