# Generated by Django 6.0.1 on 2026-07-30 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiagent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('fund_added', '新增基金'), ('invest_changed', '调整定投'), ('stopped', '停投'), ('resumed', '恢复定投'), ('cleared', '清仓'), ('edited', '编辑资料')], max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='aiagent_act_user_id_9c244b_idx')],
            },
        ),
    ]
