# Generated by Django 6.0.1 on 2026-07-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deepseek_key_enc',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
