# Generated by Django 6.0.1 on 2026-07-27 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(blank=True, max_length=16)),
                ('market', models.CharField(choices=[('CN', 'A股'), ('US', '美股')], max_length=2)),
                ('confirm_delay', models.PositiveSmallIntegerField(default=1)),
                ('invest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invest_frequency', models.CharField(choices=[('DAILY', '每日'), ('WEEKLY', '每周')], default='DAILY', max_length=6)),
                ('invest_weekday', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('start_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fund_type', models.CharField(choices=[('STOCK', '股票型'), ('MIXED', '混合型'), ('BOND', '债券型'), ('INDEX', '指数型'), ('QDII', 'QDII'), ('MONEY', '货币型')], default='INDEX', max_length=8)),
                ('risk_level', models.PositiveSmallIntegerField(choices=[(1, 'R1'), (2, 'R2'), (3, 'R3'), (4, 'R4'), (5, 'R5')], default=3)),
                ('currency', models.CharField(choices=[('CNY', '人民币'), ('USD', '美元')], default='CNY', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='funds', to='funds.tag')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
