# Generated by Django 6.0.1 on 2026-07-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_dailyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
