# Generated by Django 6.0.1 on 2026-07-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_fund_end_date_alter_dailyrecord_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
