# Generated by Django 6.0.1 on 2026-07-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_fund_is_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='fee_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
