# Generated by Django 6.0.1 on 2026-07-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_fund_fee_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('date', models.DateField()),
                ('unit_nav', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('code', 'date')},
            },
        ),
    ]
